use_frameworks!

target 'OMGenericTableView_Example' do
  pod 'OMGenericTableView', :path => '../'
  pod 'Popover'

  target 'OMGenericTableView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
